#!/bin/bash
# Inside `vagrant ssh`.

cd /var/www/presskit

php index.php > /pxn/presskit/index.html
php style.css > /pxn/presskit/style.css

# And here come the dirty hacks to make presskit work…

# -------------------------------------------------------
# Convert pages.
# -------------------------------------------------------

function convert {
  export QUERY_STRING="p=$1"
  php -e -r 'parse_str($_SERVER["QUERY_STRING"], $_GET); include "sheet.php";' > /pxn/presskit/$1.html
}

convert bulletml_for_unity
convert shmupfest
convert steredenn

# -------------------------------------------------------
# Fix links.
# -------------------------------------------------------

function fix_links {
  sed -e 's/sheet.php?p=bulletml_for_unity/bulletml_for_unity.html/g' \
      -e 's/sheet.php?p=shmupfest/shmupfest.html/g' \
      -e 's/sheet.php?p=steredenn/steredenn.html/g' \
      -e 's|sheet.php?p=credits|http://dopresskit.com/#thanks|g' \
      -e 's/index.php/index.html/g' \
      /pxn/presskit/$1.html > /tmp/tmp.html

  mv /tmp/tmp.html /pxn/presskit/$1.html
}

fix_links index

fix_links bulletml_for_unity
fix_links shmupfest
fix_links steredenn
